#File created for REST Client in VS Code https://marketplace.visualstudio.com/items?itemName=humao.rest-client
#REST Client allows you to send HTTP request and view the response in Visual Studio Code directly.

#auth:jwt:AudienceId
@client_id = f079d057929d4b3ab74eda26682ebf3c

#auth:jwt:AudienceSecret
@secretBase64 = P90Rz80gGcvzRrvASB1QxWSnqF6yf9deO5ndmRy7MIs

http://localhost:50962/api/identity/userUnprotected/SuperPowerUser


###  Get token - with clientId in body
POST http://localhost:50962/auth/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=krzyhook&password=P@ssw0rd&client_id=f079d057929d4b3ab74eda26682ebf3c

### Get token with clientId and secretKey encoded in header
POST http://localhost:50962/auth/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic ZjA3OWQwNTc5MjlkNGIzYWI3NGVkYTI2NjgyZWJmM2M6UDkwUno4MGdHY3Z6UnJ2QVNCMVF4V1NucUY2eWY5ZGVPNW5kbVJ5N01Jcw==
#Authorization: Basic Base64($CLIENT_ID:$CLIENT_SECRET) --> Base64(f079d057929d4b3ab74eda26682ebf3c:P90Rz80gGcvzRrvASB1QxWSnqF6yf9deO5ndmRy7MIs)

grant_type=password&username=krzyhook&password=P@ssw0rd


###
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoia3J6eWhvb2siLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL2FjY2Vzc2NvbnRyb2xzZXJ2aWNlLzIwMTAvMDcvY2xhaW1zL2lkZW50aXR5cHJvdmlkZXIiOiJBU1AuTkVUIElkZW50aXR5IiwiQXNwTmV0LklkZW50aXR5LlNlY3VyaXR5U3RhbXAiOiI2OGFmNDYwYS02YzY1LTQxZGUtYWQzNi1hYWJjMGY3MTExYTIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiVXNlcklkIjoiMSIsIkZpcnN0TmFtZSI6IksiLCJMYXN0TmFtZSI6IktLIiwibmJmIjoxNTEwNzc2MTgxLCJleHAiOjE1MTA4NjI1ODEsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTA5NjIiLCJhdWQiOiJmMDc5ZDA1NzkyOWQ0YjNhYjc0ZWRhMjY2ODJlYmYzYyJ9.Z6PLP3V4ErR93aP4dWPL1GXNRugcn7osA9ad8N4TChk


### Refresh token
POST http://localhost:50962/auth/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&client_id={{client_id}}&refresh_token=c1112a6038144ba6b2d7af9eb98c3222


###
GET http://localhost:50962/api/identity/user/krzyhook HTTP/1.1
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoia3J6eWhvb2siLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL2FjY2Vzc2NvbnRyb2xzZXJ2aWNlLzIwMTAvMDcvY2xhaW1zL2lkZW50aXR5cHJvdmlkZXIiOiJBU1AuTkVUIElkZW50aXR5IiwiQXNwTmV0LklkZW50aXR5LlNlY3VyaXR5U3RhbXAiOiJhNTUxMmYyMS0yZjFiLTQ5NjktYjE5ZC1kNDFkMmFiNTdhNTIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiVXNlcklkIjoiMSIsIkZpcnN0TmFtZSI6IksiLCJMYXN0TmFtZSI6IktLIiwibmJmIjoxNTEwNjkxMDQ0LCJleHAiOjE1MTA3Nzc0NDQsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTA5NjIiLCJhdWQiOiJmMDc5ZDA1NzkyOWQ0YjNhYjc0ZWRhMjY2ODJlYmYzYyJ9.ktS4k0aMxhKjDzvFE0tEm8R2x0VkQED28ODimOtfdQQ
Authorization: {{token}}

###
http://localhost:50962/api/identity/role/1
Authorization: {{token}}

###
http://localhost:50962/api/identity/roles
Authorization: {{token}}

###
http://localhost:50962/api/identity/claims
Authorization: {{token}}
